theme: jekyll-theme-cayman
name: "Niedziele wolne od handlu"

title: "Niedziele wolne od handlu"
description: "Nie wiesz które niedziele są wolne od handlu? My wiemy!\nAplikacja Czy Kupię przypomni Ci o zakupach w przeddzień abyś nie musiał chodzić głodny!"
app_store_url: "http://piszek.com"
android_url: "https://play.google.com/store/apps/details?id=com.piszek.czykupie"
google_analytics: "UA-111272274-2"
